version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: db_app
    command: -p 5455
    expose:
      - 5455
    env_file:
      - .env-deploy

  redis:
    image: redis:5
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-deploy
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 7777:8000
    depends_on:
      - db
      - redis      